name: Fixel Algorithms
markdown: kramdown
highlighter: rouge
url: http://fixelalgorithms.co
author: Davide Barranca
description: Image Processing Algorithms
include: ['.htaccess']
timezone: Italy
plugins:
    - jekyll-sitemap
    - jekyll-paginate
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/rss.xml"
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
paginate: 5
paginate_path: "/news/page:num"
permalink: /news/:year/:month/:title/index.html
